version: "3.9"
services:
  db:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shibaquests
    ports:
      - "5432:5432"
